config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'management', to: 'pages#management'
  get 'resource', to: 'pages#resource'
  get 'testusers', to: 'pages#testusers'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :testcases
  resources :testsuites
  resources :users
  resources :groups
  resources :devices

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  validates :devicetype, presence: true, length:{mimimum: 5, maximum: 25}
  validates :name, presence: true, length:{minimum: 5, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 200}  
end

app/controllers/devices_controller.rb
class DevicesController <ApplicationController
  before_action :set_device, only:[:edit, :update, :show, :destroy]
  def new
    @device = Device.new
  end
  
  def create
    @device = Device.new(params_device)
    @device.user = current_user
    if @device.save
      flash[:success] ="Device added successfully"
      redirect_to device_path(@device)
    else
      render 'new'
    end
  end
  
  def show
     
  end
  
  def index
    @devices = Device.paginate(page: params[:page], per_page: 5)
  end
  
  def edit
    
  end
  
  def update
    if @device.update(params_device)
      flash[:success] ="Device updated successfully"
      redirect_to device_path(@device)
    else
      render 'edit'
    end
  end
  def destroy
    @device.destroy
    flash[:danger] = "Device deleted successfully"
    redirect_to devices_path
  end
  
  private
  def params_device
    params.require(:device).permit(:devicetype, :name, :description, :status, :group_id)
  end
  
  def set_device
    @device = Device.find(params[:id])
  end
  
end

app/views/devices/_device.html.erb
  <div class="col-xs-12 col-xs-offset-0 well well-lg">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Group</th>
          <th scope="col">Type</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Created by</th>
          <th scope="col">Created On</th>
          <th scope="col">Updated On</th>
        </tr>
      </thead>
      <tbody>
      <% obj.each do |device| %>
          <tr>
          <td><%= link_to device.group.name, group_path(device.group) %> </td>
          <td><%= device.devicetype %></td>
          <td ><%= link_to device.name, device_path(device) %> </td>
          <td><%= truncate(device.description, length:50) %></td>
          <td><%= device.user.username if device.user%></td>
          <td><%= device.created_at.to_date %></td>
          <td><%= device.updated_at.to_date %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

app/views/devices/_form.html.erb
<%= render 'shared/errors', obj: @device %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@device, :html=> {class:"form-horizontal", role:"form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :devicetype, "Device Type" %>
      </div>
      <div class="col-sm-8">
        <%= f.select :devicetype, options_for_select(["Workstation", "Access Point", "Switch"]) %>

      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :group, "Device Group" %>
      </div>
      <div class="col-sm-8">
        <%= f.collection_select :group_id, Group.all, :id, :name %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name, "Device Name" %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter Device Name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :description, row: 10, class: "form-control", placeholder: "Enter Device Description" %>
      </div>
    </div>
    <div class="form-group">
      <div class="center col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
    <div class="center col-xs-4">
      <%= link_to "Back to Device listing", devices_path %>
    </div>
  </div>
</div>

app/views/devices/edit.html.erb
 <% if logged_in? %>
  <h1 align="center">Edit existing Device</h1>
  <%= render 'form' %>
<% end %>

app/views/devices/index.html.erb
<% if logged_in? %>
<h1 align="center"> Device list</h1>
  <div class="container">
    <%= render 'device', obj: @devices %>
    <div class= "pagination"> <%= will_paginate %> </div> 
  </div>
<% end %>

app/views/devices/new.html.erb
<% if logged_in? %>
  <h1 align="center">Add Device</h1>
  <%= render 'form' %>
<% end %>

app/views/devices/show.html.erb
 <% if logged_in? %>
  <div class="well col-xs-8 col-xs-offset-2">
    <h3 align="left"><strong>Device Name:</strong> <%= @device.name %></h2>
    <h3 align="left"><strong>Device Type:</strong> <%= @device.devicetype %></h2>
    <h3 align="left"><strong>Device Group:</strong> <%= @device.group.name %></h2>
    <h3 class="left description"><strong>Description:</strong></h4> <%= @device.description %>
    <div class="article-actions">
      <%= link_to "Edit Device", edit_device_path(@device), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete Device", device_path(@device), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete the article?"}, 
                                          class: "btn btn-xs btn-danger" %>
      <%= link_to "View all Device", devices_path, class: "btn btn-xs btn-success" %>
  </div>
</div>
<% end %>