config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'management', to: 'pages#management'
  get 'resource', to: 'pages#resource'
  get 'testusers', to: 'pages#testusers'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :testcases
  resources :testsuites
  resources :users
  resources :groups
  resources :devices

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :devices
  validates :name, presence: true, length:{minimum: 4, maximum: 100}
  validates :description, presence: true, length:{minimum: 4, maximum: 200}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_testsuite, only:[:edit, :update, :show, :destroy]
  before_action :require_user
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      flash[:success] = "Group added successfully"
      redirect_to group_path(@group)
    else
      render 'new'
    end      
  end
  
  def show
    @group_devices = @group.devices.paginate(page: params[:page], per_page: 5)
  end
  def edit
   
  end
  
  def update
     if @group.update(group_params)
      flash[:success] = "Group updated successfully"
      redirect_to group_path(@group)
    else
      render 'edit'
    end  
  end
  def index
    @groups = Group.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @group.destroy
    flash[:danger] = "Group deleted successfully"
    redirect_to groups_path
  end
  
  private
  def group_params
    params.require(:group).permit(:name, :description)
  end
  def set_testsuite
    @group = Group.find(params[:id])
  end
  
end

app/views/groups/_form.html.erb
<%= render 'shared/errors', obj: @group %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@group, :html=> {class:"form-horizontal", role:"form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name, "Group Name" %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Name of Group", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :description, row: 10, class: "form-control", placeholder: "Description for Group" %>
      </div>
    </div>
    <div class="form-group">
      <div class="center col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
    <div class="center col-xs-4">
      <%= link_to "Back to Group listing", groups_path %>
    </div>
  </div>
</div>

app/views/groups/_group.html.erb
  <div class="col-xs-12 col-xs-offset-0 well well-lg">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Group Name</th>
          <th scope="col">Device Count</th>
          <th scope="col">Description</th>
          <th scope="col">Created by</th>
          <th scope="col">Created On</th>
          <th scope="col">Updated On</th>
        </tr>
      </thead>
      <tbody>
      <% obj.each do |group| %>
          <tr>
          <td><%= link_to group.name, group_path(group) %> </td>
          <td > 3 </td>
          <td><%= truncate(group.description, length:50) %></td>
          <td><%= group.user.username if group.user%></td>
          <td><%= group.created_at.to_date %></td>
          <td><%= group.updated_at.to_date %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

app/views/groups/edit.html.erb
 <% if logged_in? %>
  <h1 align="center">Edit existing Group</h1>
  <%= render 'form' %>
<% end %>

app/views/groups/index.html.erb
<% if logged_in? %>
  <div class="container">
    <%= render 'group', obj: @groups %>
    <div class= "pagination"> <%= will_paginate %> </div> 
  </div>
<% end %>

app/views/groups/new.html.erb
<% if logged_in? %>
  <h1 align="center">Create Group</h1>
  <%= render 'form' %>
<% end %>

app/views/groups/show.html.erb
 <% if logged_in? %>
<h1 align="center"> Group Details </h1>
  <div class="well col-xs-10 col-xs-offset-1">
    <h3 align="left"><strong>Group Name:</strong> <%= @group.name %></h2>
    <h3 class="left description"><strong>Description:</strong></h4>
    <%= simple_format(@group.description) %>
    <div class="article-actions">
      <%= link_to "Edit Group", edit_group_path(@group), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete Group", group_path(@group), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete the article?"}, 
                                          class: "btn btn-xs btn-danger" %>
      <%= link_to "View all Groups", groups_path, class: "btn btn-xs btn-success" %>
  </div>
    <h4>
      Devices Assigned to Group
    </h4>
    <%= render 'devices/device', obj: @group_devices %>
    <%= will_paginate @group_devices %> 
</div>
<% end %>