config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'management', to: 'pages#management'
  get 'resource', to: 'pages#resource'
  get 'testusers', to: 'pages#testusers'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :testcases
  resources :testsuites
  resources :users
  resources :groups
  resources :devices

end

app/models/testsuite.rb
class Testsuite < ActiveRecord::Base
  belongs_to :user
  has_many :testcases
  validates :title, presence: true, length:{minimum: 4, maximum: 100}
  validates :description, presence: true, length:{minimum: 4, maximum: 200}
end

app/controllers/testsuites_controller.rb
class TestsuitesController < ApplicationController
  before_action :set_testsuite, only:[:edit, :update, :show, :destroy]
  before_action :require_user
  def new
    @testsuite = Testsuite.new
  end
  def create
    @testsuite = Testsuite.new(testsuite_params)
    @testsuite.user = current_user
    if @testsuite.save
      flash[:success] ="Testsuite created uccessfully"
      redirect_to testsuite_path(@testsuite)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @testsuite.update(testsuite_params)
      flash[:success] ="Testsuite updated successfully"
      redirect_to testsuite_path(@testsuite)
    else
      render 'edit'
    end
  end
  
  def show
    @testsuite_testcases = @testsuite.testcases.paginate(page: params[:page], per_page: 5)
  end
  
  def index
#     @testsuites = Testsuite.all
    @testsuites = Testsuite.paginate(page: params[:page], per_page: 5)
  end
  def destroy
    @testsuite.destroy
    flash[:danger] = "Testsuite deleted successfully"
    redirect_to testsuites_path
  end
  
  private
  def testsuite_params
     params.require(:testsuite).permit(:title, :description)
  end
  def set_testsuite
    @testsuite = Testsuite.find(params[:id])
  end
end

app/views/testsuites/_form.html.erb
<%= render 'shared/errors', obj: @testsuite %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@testsuite, :html=> {class:"form-horizontal", role:"form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title, "Testsuite Name" %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Name of Testsuite", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :description, row: 10, class: "form-control", placeholder: "Description for Testsuite" %>
      </div>
    </div>
    <div class="form-group">
      <div class="center col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
    <div class="center col-xs-4">
      <%= link_to "Back to testcase listing", testcases_path %>
    </div>
  </div>
</div>

app/views/testsuites/_testsuite.html.erb
  <div class="col-xs-12 col-xs-offset-0 well well-lg">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Testsuite Name</th>
          <th scope="col">Testcase Count</th>
          <th scope="col">Description</th>
          <th scope="col">Created by</th>
          <th scope="col">Created On</th>
          <th scope="col">Updated On</th>
          <th scope="col">Assigned To</th>
        </tr>
      </thead>
      <tbody>
      <% obj.each do |testsuite| %>
          <tr>
          <td><%= link_to testsuite.title, testsuite_path(testsuite) %> </td>
          <td class="center"><%= link_to testsuite.testcases.count, testsuite_path(testsuite) %></td>
          <td><%= truncate(testsuite.description, length:50) %></td>
          <td><%= testsuite.user.username if testsuite.user%></td>
          <td><%= testsuite.created_at.to_date %></td>
          <td><%= testsuite.updated_at.to_date %></td>
          <td>Kartik Aiyar</td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

app/views/testsuites/edit.html.erb
  <% if logged_in? %>
<h1 align="center">Edit existing Testsuite</h1>
<%= render 'form' %>
<% end %>

app/views/testsuites/index.html.erb
  <% if logged_in? %>
<div class="container">
  <%= render 'testsuite', obj: @testsuites %>
  <div class= "pagination"> <%= will_paginate %> </div> 
</div>
<% end %>

app/views/testsuites/new.html.erb
<% if logged_in? %>
<h1 align="center">Create Testsuite</h1>
<%= render 'form' %>
<% end %>

app/views/testsuites/show.html.erb
 <% if logged_in? %>
  <div class="well col-xs-10 col-xs-offset-1">
    <h3 align="left"><strong>Testsuite Name:</strong> <%= @testsuite.title %></h2>
    <h3 class="left description"><strong>Description:</strong></h4>
    <%= simple_format(@testsuite.description) %>
    <div class="article-actions">
      <%= link_to "Edit Testsuite", edit_testsuite_path(@testsuite), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete Testsuite", testsuite_path(@testsuite), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete the article?"}, 
                                          class: "btn btn-xs btn-danger" %>
      <%= link_to "View all Testsuites", testsuites_path, class: "btn btn-xs btn-success" %>
  </div>
    <h4>
      Testcases assigned to Testsuite
    </h4>
    <%= render 'testcases/testcase', obj: @testsuite_testcases %>
    <%= will_paginate @testsuite_testcases %> 
</div>
<% end %>