config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'management', to: 'pages#management'
  get 'resource', to: 'pages#resource'
  get 'testusers', to: 'pages#testusers'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :testcases
  resources :testsuites
  resources :users
  resources :groups
  resources :devices

end

app/views/layouts/_footer.html.erb
<div class="container">

<footer class="footer">

<small>

Copyright © <a href="enter in a link here">Riverbed Test Management</a>

by <a href="enter in a link here">Kartik Aiyar</a>

</small>

<nav>

<ul>

<li><%= link_to "About", about_path %></li>

</ul>

</nav>

</footer>

</div>

app/views/layouts/_messages.html.erb
<div class="row">
<div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Riverbed Test Management", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <% if logged_in? %>
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Test Execution", testcases_path %></li>
        <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Test Management <span class="caret"></span></a>
          <ul class="dropdown-menu"> 
            <li><%= link_to "Create Testcase", new_testcase_path %></li>
            <li><%= link_to "Create Testsuite", new_testsuite_path %></li>
            <li><%= link_to "View all Testcases", testcases_path %></li>
            <li><%= link_to "View all Testsuites", testsuites_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Test Management", management_path %></li>
          </ul>
        </li>        
        <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Test Resource <span class="caret"></span></a>
          <ul class="dropdown-menu"> 
            <li><%= link_to "Add Device", new_device_path %></li>
            <li><%= link_to "Add Group", new_group_path %></li>
            <li><%= link_to "View all Devices", devices_path %></li>
            <li><%= link_to "View all Groups", groups_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Test Resources", resource_path %></li>
          </ul>
        </li>
        <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Test Users <span class="caret"></span></a>
          <ul class="dropdown-menu"> 
            <li><%= link_to "Add new user", new_user_path %></li>
            <li><%= link_to "View all Users", users_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Test Users", testusers_path %></li>
          </ul>
        </li>
        <li><%= link_to "Test Reports", testcases_path %></li>
        <li><%= link_to "Test Projects", testcases_path %></li>     
      </ul>
      <% end %>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riverbed Test Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>